name: Cypress Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ vars.BASE_URL }}
      EMAIL: ${{ vars.EMAIL }}
      PASSWORD: ${{ vars.PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Generate .env File for dotenv
        run: |
          echo "BASE_URL=${{ vars.BASE_URL }}" >> .env
          echo "EMAIL=${{ vars.EMAIL }}" >> .env
          echo "PASSWORD=${{ vars.PASSWORD }}" >> .env

      - name: Run Cypress Tests
        run: yarn cypress run

      - name: Upload Cypress Videos (On Failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/
