name: Cypress Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ vars.BASE_URL }}
      EMAIL: ${{ vars.EMAIL }}
      PASSWORD: ${{ vars.PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Verify Environment Variables
        run: |
          if [ -z "$BASE_URL" ]; then echo "BASE_URL is not set" && exit 1; fi
        shell: bash

      - name: Run Cypress Tests
        env:
          BASE_URL: $BASE_URL
          EMAIL: $EMAIL
          PASSWORD: $PASSWORD
        run: yarn cypress run
        shell: bash

      - name: Upload Cypress Videos (On Failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/
          shell: bash

      - name: Upload Cypress Screenshots (On Failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
          shell: bash
        

